### PR TITLE
Avoid memory corruption in data processing

### PR DESCRIPTION
**Pull request by chadrockey**
In a system with two microscan3 present, there are occasionally driver crashes with double frees, segmentation faults, or other memory corruption.

My theory is that very rarely, something causes one of the std::vectors to reallocate its memory (likely the insert or resize functions), invalidating the raw pointers already used in other parts of the code.

The proposed fix here is to use std::shared_ptr<std::vector<uint8_t>> as the core buffer and always duplicate or copy the data instead of modifying it in place.

Secondarily, use STL constructs to make it more visible to a reader that the data structure is a std::vector.

@puck-fzi I want to give this a week or so of testing to confirm that it resolves the issues without introducing new ones.  I also really need your input because there are so many lines of code modified here.

### CODE REVIEW

**Comment by puck-fzi** [comment]
Hey together, I was not able to reproduce your mentioned errors yet. I had two sensors and drivers working on a mobile platform here. How often do the errors occur?
@chadrockey  Did your proposed changes help you? Did they resolve the problems for you?

**Comment by chadrockey** [comment]
@puck-fzi Thanks for the update.  We've had some success, but not enough to tell you that it's resolved.  Still pending more testing.  I'll keep you updated and will check in one week from now.

Our configuration also has a new SICK Microscan GEPR in the mix, is it possible this is the source of the errors?  I suspect there are rogue packets somewhere.

**Comment by puck-fzi** [comment]
Hey, this might be a cause for an error, but I could not say for sure. The setup I used only had two microScan3 Pro with a range of 5.5m on the platform. With this setup I did not get any errors. So I suspect it will be some other component creating troubles. This setup was running for a few hours last week without causing any troubles. So I still can't reproduce the mentioned error. But I am happy to integrate a fix which resolves your troubles.

**Comment by chadrockey** [comment]
Thanks for checking in, we're still testing this, but it does look promising.  Could you check that there are no regressions and that it works properly for you?

**Comment by puck-fzi** [comment]
Hi, sorry for the delay. I will still need some time for testing and checking. Any news and/or concerns on your side?

**Comment by chadrockey** [comment]
@puck-fzi Things have looked good over here.  It's quite a substantial change, but stability has been improved without any known negative effects.

**Comment by puck-fzi** [comment]
Sorry it took some time, I tested your changes and finally managed to merge your request.
I did not find any regressions so far. Thank you for your contribution

**Pull request merged**
