### PR TITLE
Quick and dirty fix to exit if no tcp connection is reached

### PR DESCRIPTION
**Pull request by Hunk86**
Hello,

can we merge this Branch ? For us it is very important that we have some handling, when the connection couldn't be established.

I did it with rethrow the exception but this solution is also ok

For the use case it is important, that when no scanner is reachable the node reacts to this. Only then the highlevel Application can decide if it want to restart the node for example.

### CODE REVIEW

**Comment by puck-fzi** [comment]
Hi, this is nothing I would merge like this into the master branch. As the commit message says this is a quick fix and not proper error handling. I could rebase this branch on the current master, so it is an up to date version.
However, for a merge in the master a proper error handling should be implemented and not such a quick fix.
Currently I will not find time to implement this, but feel free to contribute. I am happy to discuss any merge requests.

**Comment by Hunk86** [comment]
It would be really nice if you rebase this with master

What is your vision for a proper error handling ? Auto reconnect or good shut down of the node?

**Comment by puck-fzi** [comment]
The ideal case would be a few reconnect tries with a good shutdown if unsuccessful, however a clean shutdown with proper error handling would be sufficient i suppose. Most of the time when the connection cannot be made i guess the fault lies in an incorrect setup. So far once started i never had the problems of loosing the connection

**Comment by puck-fzi** [comment]
Rebased it with the current master. So now once the tcp connection times out it will exit the node

**Pull request closed without merging**
