### PR TITLE
DeviceStatus Requests

### PR DESCRIPTION
**Pull request by Jmeyer1292**
Hey @puck-fzi!

I'm back to working on the SICK integration into my robot and I'm trying to automatically estimate the time offset between my computer's steady clock and the sensor's own clock so that I can better synchronize the SICK with other sensors.

To this end, I've implemented the `device status` command from the COLA protocol so that I can ping the sensors system time directly. 

This PR is not in a final state as there are many style related things to clean up, but I wanted to gauge your opinion on accepting this contribution.

The other issue is this: I want to be able to send a request to the scanner and have it respond as quickly as possible so that we get the best estimate for what the UDP packets will see for network transmission delay. This means that I want some code that looks like this:
```c++
auto start_time = std::chrono::steady_clock::now();
requestDeviceStatus(device_status);
auto end_time = std::chrono::steady_clock::now();
```

The current command architecture starts a new cola session (and thus TCP connection) on every request which skews the estimated delay by a lot. Would you be opposed to a dedicated function in `Sicksafetyscanners` that attempts to compute the offset during a single session?

Thanks,
Jon

### CODE REVIEW

**Comment by puck-fzi** [comment]
Hi Jon, thanks for your contribution. I will have a look into it, but it might take some time. The device status will be added to the functions. For your second part, I am not quiet sure I understand you correctly. You want a permanent TCP connection? Would it not be enough to wrap the lines of code in a session. If you start first the session, then you can do your calculations and then end the session or do you want to always check the time and dynamically adapt your sync? 
Additionally, I am not sure if using the TCP connection is the best way to check for network delays for the UDP packets. Would it not make sense maybe using the timestamps of the scan in the UDP data header to calculate your offset?

**Comment by Jmeyer1292** [comment]
@puck-fzi Thanks for getting back to me. Sorry I've been out of work for a while on medical leave.

My memory is a little fuzzy but what I was after was a way of creating a Cola session, running many requests through it, and then closing it. That's what I ended up adding for myself. The issue was I couldn't figure out how to create/close a session and send device requests through the public interface to the `SickSafetyscanners` class.

So fundamentally, when I connect to the scanner, I want to estimate the time offset between my computer's steady clock and the (presumably real-time, monotonic, etc) clock on the scanner. My thought process is to use some super simple version of NTP: I ask the scanner what time it is and it responds as quickly as possible. If network transmission was instant, then I think I could just subtract the difference in our clocks and be done. If it takes time, then I assume that the sensor got the request half way through the call-response delay and add this to the clock difference. Whatever offset I find, I then apply to each laser scan as it comes in so that all sensor data timestamps are in the "same clock".

Have you dealt with this sort of thing in the past?

**Comment by puck-fzi** [comment]
Hi, there is a dynamic configurable parameter time_offset. That can be used to adapt the timestamps of the ros message for latency etc. There is no function to determine the diff in the clocks though. To do that properly you would need a continuous polling and that produces quiet a bit of overhead.

**Comment by puck-fzi** [comment]
Currently all cola2 variables are in progress. I will close this merge request.

**Pull request closed without merging**
